---
title: "Teacher Turnover in Wisconsin"
author: "Michael Chirico"
date: "March 17, 2017"
output:
  pdf_document:
    keep_tex: yes
    includes:
      in_header: turnover_paper_header.tex
abstract: 'Turnover in Wisconsin'
bibliography: references.bib
link-citations: true
---

```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'hide')
knitr::read_chunk('turnover_data_cleaner.R')
library(xtable)
options(xtable.comment = FALSE)
options(xtable.include.rownames = FALSE)
library(data.table)
library(texreg)
```

```{r start_read, cache = TRUE, include = FALSE}
```

# Introduction

# Data

# Results

```{r table_1, warning = FALSE, results = 'asis', message = FALSE}
library(funchir)
T1 = rbind(
  teachers[ , .(`Remain in Same School` = 100*sum(!move_school_next)/.N,
                `Change Schools Within District` = 
                  100*sum(move_within_next)/.N,
                `Switch Districts` = 100*sum(move_district_next)/.N,
                `Exit Wisconsin \\mbox{Public Schools}` = 100*sum(quit_next)/.N,
                `Number of Teachers` = prettyNum(.N, big.mark = ',')),
            keyby = .(`Teacher Experience` = exp_split)],
  teachers[ , .(`Teacher Experience` = 'All',
                `Remain in Same School` = 100*sum(!move_school_next)/.N,
                `Change Schools Within District` = 
                  100*sum(move_within_next)/.N,
                `Switch Districts` = 100*sum(move_district_next)/.N,
                `Exit Wisconsin \\mbox{Public Schools}` = 100*sum(quit_next)/.N,
                `Number of Teachers` = prettyNum(.N, big.mark = ','))])
tbl = capture.output(print(xtable(
  T1, caption = 'Year-to-year Transitions of Teachers by Experience, 2000-08', 
  label = 'tbl:move_by_exp', digits = 1L, 
  align = paste0('lp{.103\\linewidth}p{.14\\linewidth}',
                 'p{.15\\linewidth}p{.09\\linewidth}p{.16\\linewidth}R{.16}')),
  sanitize.text.function = identity))
idx = grep('^Teacher', tbl) - 1L
tbl = c(tbl[1L:idx], 
        ' & \\multicolumn{4}{c}{Percent of Teachers Who} & \\\\ \\cline{2-5}',
        tbl[(idx+1L):length(tbl)])
cat(tbl, sep = '\n')
```

```{r table_2, results = 'asis'}
share_change = 
  #use 2006, not incl_rng, because of the artificial change in 
  #  shares induced by the change in how urbanicity is calculated
  teachers[year %in% c(2000, 2006), .N, by = .(year, urbanicity_s)
           ][ , shr := N/sum(N), by = year
              ][order(year), .(delta = diff(shr)), by = urbanicity_s]
T2 = rbind(
  teachers[ , {
    idx = move_district_next
    N_move = sum(idx)
    c(as.list(table2(urbanicity_s_next[idx], prop = TRUE, pct = TRUE)),
      list(n_change = prettyNum(N_move, big.mark = ','), 
           pct_origin = 100*N_move/.N,
           change_share = 
             share_change[.BY, sprintf('%.1f\\%%', 100*delta), on = 'urbanicity_s']))
  }, keyby = urbanicity_s],
  teachers[total_exp_floor <= 3, {
    idx = move_district_next
    N_move = sum(idx)
    c(as.list(table2(urbanicity_s_next[idx], prop = TRUE, pct = TRUE)),
      list(n_change = prettyNum(N_move, big.mark = ','), 
           pct_origin = 100*N_move/.N))
  }, keyby = urbanicity_s],
  fill = TRUE)

setnames(T2, grep('[^y]_', names(T2)), character(3L))
T2[ , c('Origin Community', 'urbanicity_s') :=
      .(paste0('\\quad ', urbanicity_s), NULL)]
setcolorder(T2, c(ncol(T2), seq_len(ncol(T2) - 1L)))

tbl = capture.output(print(xtable(
  T2, caption = paste('Destination Community Type for Teachers',
                      'Changing Districts, by Origin Community',
                      'Type and Teacher Experience Level'),
  label = 'tbl:markov', digits = 1L, align = 'llrrrrrrr'),
  sanitize.text.function = identity, floating.environment = 'sidewaystable'))
idx = grep('^Origin', tbl)
mrow = function(x, n) paste0('\\multirow{', n, '}{*}{', x, '}')
mcol = function(x, n) paste0('\\multicolumn{', n, '}{c}{', x, '}')
pbox = function(x, p) paste0('\\parbox{', p, '\\linewidth}{', x, '}')
tbl = c(tbl[1L:(idx - 1L)],
        paste0(paste('', mcol(mrow('Percent of Teachers Who Move to', 2), 4),
                     mrow(pbox('Number Teachers Changing Districts', .09), 4),
                     mrow(pbox('Percent of Origin Teachers', .07), 4),
                     mrow(pbox('Change in Share of Teachers 2000-06', .07), 4), 
                     sep = ' & '), '\\\\'),
        ' & \\multicolumn{4}{c}{} & & & \\\\ \\cline{2-5}',
        '& & & & & & & \\\\', tbl[idx + 0L:1L],
        'I. All teachers & & & & & & & \\\\', tbl[idx + (2L:5L)], 
        '\\multicolumn{3}{l}{II. Probationary teachers ' %+% 
          '(1-3 years experience)}' %+%
          ' & & & & & \\\\', tbl[(idx+6L):length(tbl)])
cat(tbl, sep = '\n')
```

```{r table_3, results = 'asis'}
T3 = 
  teachers[move_district_next & total_exp_floor <= 10, {
    dl = lapply(
      list(schedule_lsalary_next - schedule_lsalary_next_cf,
           schedule_lsalary_resid_next - schedule_lsalary_resid_next_cf,
           pct_prof_next_d - pct_prof_d, pct_hisp_next_d - pct_hisp_d,
           pct_black_next_d - pct_black_d, pct_frl_next_d - pct_frl_d),
      na.omit)
    .(var = paste0(rep(seq_len(6L), each = 2L), rep(c('M', 'S'), 6L)),
      val = c(rbind(sapply(dl, mean),
                    sapply(dl, function(x) sd(x)/sqrt(length(x))))))
  }, keyby = .(exp_split, gender)
  ][ , dcast(.SD, var ~ gender + exp_split, value.var = 'val')]
T3[ , all := 
      teachers[move_district_next & total_exp_floor <= 10, {
        dl = lapply(
          list(schedule_lsalary_next - schedule_lsalary_next_cf,
               schedule_lsalary_resid_next - schedule_lsalary_resid_next_cf,
               pct_prof_next_d - pct_prof_d, pct_hisp_next_d - pct_hisp_d,
               pct_black_next_d - pct_black_d, pct_frl_next_d - pct_frl_d),
          na.omit)
        c(rbind(sapply(dl, mean),
                sapply(dl, function(x) sd(x)/sqrt(length(x)))))}]]

T3[ , var := rep(c('Base year salary (log)', 'Adjusted salary (log)',
                   'Percent proficient', 'Percent Hispanic',
                   'Percent black', 'Percent subsidized lunch'), each = 2L)]
T3[ , type := rep(c('m', 's'), 6L)]
cols = setdiff(names(T3), c('var', 'type'))
sidx = T3$type == 's'
pidx = grepl('^Percent', T3$var)
T3[ , (cols) := lapply(.SD, function(x) {
  o = character(length(x))
  o[!pidx & !sidx] = sprintf('%.3f', x[!pidx & !sidx])
  o[!pidx & sidx] = sprintf('(%.3f)', x[!pidx & sidx])
  o[pidx & !sidx] = sprintf('%.1f%%', 100*x[pidx & !sidx])
  o[pidx & sidx] = sprintf('(%.1f%%)', 100*x[pidx & sidx])
  o}), .SDcols = cols]
T3[type == 's', var := '']
T3[ , type := NULL]
setnames(T3, c('', rep(exp_lab[1L:3L], 2L), ''))

tbl = capture.output(print(xtable(
  T3, caption = paste('Average Change in Salary and District Student',
                      'Characteristics (and Standard Deviations) for',
                      'Teachers Changing Districts, by Gender and Experience'),
  label = 'tbl:change_by_ge', align = 'llccccccc'), 
  floating.environment = 'sidewaystable'))

idx = grep('years', tbl)

tbl = c(tbl[1L:(idx - 1L)],
        paste0(paste('', mcol('Men by Experience Class', 3L),
                     mcol('Women by Experience Class', 3L),
                     mrow(pbox('All Teachers 0-9 Years', .09), 2L),
                     sep = ' & '), '\\\\ \\cline{2-4} \\cline{5-7}'),
        tbl[idx:length(tbl)])

cat(tbl, sep = '\n')
```

```{r table_4, results = 'asis'}
T4D = 
  teachers[move_district_next & urbanicity_next_d == 'Suburban' & 
             urbanicity_d %in% c('Large Urban', 'Suburban') & 
             total_exp_floor <= 10, {
    dl = lapply(
      list(schedule_lsalary_next - schedule_lsalary_next_cf,
           schedule_lsalary_resid_next - schedule_lsalary_resid_next_cf,
           pct_prof_next_d - pct_prof_d, pct_hisp_next_d - pct_hisp_d,
           pct_black_next_d - pct_black_d, pct_frl_next_d - pct_frl_d),
      na.omit)
    .(var = paste0(rep(seq_len(6L), each = 2L), rep(c('M', 'S'), 6L)),
      val = c(rbind(sapply(dl, mean),
                    sapply(dl, function(x) sd(x)/sqrt(length(x))))))
  }, keyby = urbanicity_d
  ][ , dcast(.SD, var ~ urbanicity_d, value.var = 'val')]

T4S = 
  teachers[move_district_next & urbanicity_next_d == 'Suburban' & 
             urbanicity_d %in% c('Large Urban', 'Suburban') & 
             total_exp_floor <= 10, {
    dl = lapply(
      list(pct_prof_next_s - pct_prof_s, pct_hisp_next_s - pct_hisp_s,
           pct_black_next_s - pct_black_s, pct_frl_next_s - pct_frl_s),
      na.omit)
    .(var = paste0(rep(3L:6L, each = 2L), rep(c('M', 'S'), 4L)),
      val = c(rbind(sapply(dl, mean),
                    sapply(dl, function(x) sd(x)/sqrt(length(x))))))
  }, keyby = urbanicity_d
  ][ , dcast(.SD, var ~ urbanicity_d, value.var = 'val')]

T4 = merge(T4D, T4S, by = 'var', all.x = TRUE)

T4[ , var := rep(c('Base year salary (log)', 'Adjusted salary (log)',
                   'Percent proficient', 'Percent Hispanic',
                   'Percent black', 'Percent subsidized lunch'), each = 2L)]
T4[ , type := rep(c('m', 's'), 6L)]
cols = setdiff(names(T4), c('var', 'type'))
sidx = T4$type == 's'
pidx = grepl('^Percent', T4$var)
T4[ , (cols) := lapply(.SD, function(x) {
  o = character(length(x))
  o[!pidx & !sidx] = sprintf('%.3f', x[!pidx & !sidx])
  o[!pidx & sidx] = sprintf('(%.3f)', x[!pidx & sidx])
  o[pidx & !sidx] = sprintf('%.1f%%', 100*x[pidx & !sidx])
  o[pidx & sidx] = sprintf('(%.1f%%)', 100*x[pidx & sidx])
  o[is.na(x) & !sidx] = '---'
  o[is.na(x) & sidx] = ''
  o}), .SDcols = cols]
T4[type == 's', var := '']
T4[ , type := NULL]

tbl = capture.output(print(xtable(
  T4, caption = paste('Average Change in Salary and in District and Campus',
                      'Student Characteristics (and Standard Deviations)',
                      'for Teachers with 1-10 Years of Experience Who',
                      'Change Districts, by Community Type of Origin',
                      'and Destination District'),
  label = 'tbl:change_by_urb', 
  align = paste0('llp{.16\\textwidth}p{.16\\textwidth}',
                 'p{.16\\textwidth}p{.16\\textwidth}'))))

idx = grep('Urban', tbl)

tbl = c(tbl[1L:(idx - 1L)],
        paste0(paste('', mcol('District Average Characteristics', 2L),
                     mcol('Campus Average Characteristics', 2L),
                     sep = ' & '), '\\\\ \\cline{2-5}'),
        ' & Large Urban to Suburban & Suburban to Suburban & ' %+%
          'Large Urban to Suburban & Suburban to Suburban \\\\',
        tbl[(idx + 1L):length(tbl)])

cat(tbl, sep = '\n')
```

```{r table_5, results = 'asis'}
T5D = 
  teachers[move_district_next & total_exp_floor <= 10 & 
           ethnicity_main %in% c('Black', 'Hispanic'), {
    dl = lapply(
      list(pct_prof_next_s - pct_prof_s, pct_hisp_next_s - pct_hisp_s,
           pct_black_next_s - pct_black_s, pct_frl_next_s - pct_frl_s),
      na.omit)
    .(var = c(paste0(rep(1L:4L, each = 2L), rep(c('M', 'S'), 4L)), 'N'),
      val = c(rbind(sapply(dl, mean),
                    sapply(dl, function(x) sd(x)/sqrt(length(x)))), .N))
  }, keyby = ethnicity_main
  ][ , dcast(.SD, var ~ ethnicity_main, value.var = 'val')]

T5S = 
  teachers[move_within_next & total_exp_floor <= 10 & 
           ethnicity_main %in% c('Black', 'Hispanic'), {
    dl = lapply(
      list(pct_prof_next_s - pct_prof_s, pct_hisp_next_s - pct_hisp_s,
           pct_black_next_s - pct_black_s, pct_frl_next_s - pct_frl_s),
      na.omit)
    .(var = c(paste0(rep(1L:4L, each = 2L), rep(c('M', 'S'), 4L)), 'N'),
      val = c(rbind(sapply(dl, mean),
                    sapply(dl, function(x) sd(x)/sqrt(length(x)))), .N))
  }, keyby = ethnicity_main
  ][ , dcast(.SD, var ~ ethnicity_main, value.var = 'val')]

T5 = merge(T5D, T5S, by = 'var', all.x = TRUE)

T5[ , var := rep(c('Percent proficient', 'Percent Hispanic',
                   'Percent black', 'Percent subsidized lunch',
                   'Number of teachers'), c(2L, 2L, 2L, 2L, 1L))]
T5[ , type := c(rep(c('m', 's'), 4L), 'n')]
cols = setdiff(names(T5), c('var', 'type'))
sidx = T5$type == 's'
pidx = grepl('^Percent', T5$var)
nidx = T5$type == 'n'
T5[ , (cols) := lapply(.SD, function(x) {
  o = character(length(x))
  o[pidx & !sidx] = sprintf('%.1f%%', 100*x[pidx & !sidx])
  o[pidx & sidx] = sprintf('(%.1f%%)', 100*x[pidx & sidx])
  o[nidx] = prettyNum(x[nidx], big.mark = ',')
  o}), .SDcols = cols]
T5[type == 's', var := '']
T5[ , type := NULL]

tbl = capture.output(print(xtable(
  T5, caption = paste('Average Change in District and Campus Student',
                      'Characteristics (and Standard Deviations)',
                      'for Black and Hispanic Teachers with 1-10',
                      'Years of Experience who Change Campuses'),
  label = 'tbl:change_by_eth', 
  align = paste0('llp{.16\\textwidth}p{.16\\textwidth}',
                 'p{.16\\textwidth}p{.16\\textwidth}'))))

idx = grep('Black.x', tbl)

tbl = c(tbl[1L:(idx - 1L)],
        paste0(paste('', mcol('Between District Moves', 2L),
                     mcol('Within District Moves', 2L),
                     sep = ' & '), '\\\\ \\cline{2-5}'),
        ' & Black Teachers & Hispanic Teachers & ' %+%
          'Black Teachers & Hispanic Teachers \\\\',
        tbl[(idx + 1L):length(tbl)])

cat(tbl, sep = '\n')
```

```{r table_6, results = 'asis'}
T6 = 
  melt(teachers, id.vars = c('year', 'move_district_next', 
                             'move_within_next', 'quit_next'), 
       measure.vars = paste0(q_var, '_q'), na.rm = TRUE, value.factor = TRUE
       )[ , .(`Probability Teachers Move to New School within District` = 
                mean(move_within_next),
              `Probability Teachers Move to New District` = 
                mean(move_district_next),
              `Probability Teachers Exit Public Schools` = 
                mean(quit_next)), 
          keyby = .(variable, value)]
T6[variable == 'lwage_resid_avg_q', grep('within', names(T6)) := NA]
T6[ , variable := NULL]
cols = grep('^Prob', names(T6))
T6[ , (cols) := lapply(.SD, function(x) {
  o = sprintf('%.1f\\%%', 100*x)
  is.na(o) = is.na(x); o}), .SDcols = cols]
T6[ , value := paste0('\\quad ', value)]
setnames(T6, 'value', 'Quartile of Distribution')
  
tbl = capture.output(print(xtable(
  T6, caption = paste('School Average Transition Rates by Distribution of',
                      'Residual Teacher Salary and Student Demographic',
                      'Characteristics (data weighted by number of',
                      'teachers in school)'),
  label = 'tbl:change_by_quartile',
  align = 'lp{.4\\textwidth}p{.2\\textwidth}p{.2\\textwidth}p{.2\\textwidth}'), 
  sanitize.text.function = identity, NA.string = '---'))

idx = grep('Highest', tbl)
tbl[idx] = paste0(c('Residual salary', 'Percent proficient',
                    'Percent eligible for reduced-price lunch',
                    'Percent Black', 'Percent Hispanic'),
                  ' & & & \\\\\n', tbl[idx])
cat(tbl, sep = '\n')
```

```{r table_7, results = 'asis'}
reg_l = 
  lapply(split(teachers, f = teachers$exp_split),
         function(DT) 
           DT[ , lm(move_district_next ~
                      schedule_lbase_ba_salary*gender + 
                      pct_prof_s + pct_frl_s + 
                      ethnicity_main*pct_black_s + 
                      ethnicity_main*pct_hisp_s + factor(year) + 
                      urbanicity_s + total_exp_floor + 
                      I(total_exp_floor^2) + n_students_d + class_size_d)])

coefn = setNames(nm = names(coef(reg_l[[1L]])))
coefn[seq_len(length(coefn))] = 'x'
idx = match(c('schedule_lbase_ba_salary', 'schedule_lbase_ba_salary:genderF',
              'pct_prof_s', 'pct_frl_s', 'pct_black_s', 'pct_hisp_s',
              paste0('ethnicity_main', 
                     c('Black', 'Black', 'Hispanic', 'Hispanic'), ':pct_',
                     c('black', 'hisp', 'black', 'hisp'), '_s')), names(coefn))
coefn[idx] = 
  c('First year base salary (log)', 'First year base salary (log) * female',
    'Percent proficient', 'Percent eligible for subsidized lunch',
    'Percent Black', 'Percent Hispanic', 'Black * percent Black',
    'Black * percent Hispanic', 'Hispanic * percent Black',
    'Hispanic * percent Hispanic')
reg_l = lapply(reg_l, function(x) {
  names(x$coefficients) = coefn[names(coef(x))]; x})
tbl = capture.output(texreg(
  reg_l, omit.coef = '^x', label = 'tbl:reg_lpm', 
  caption = paste('Estimated Effects of Starting Teacher Salary and Student',
                  'Demographic Characteristics on the Probability that',
                  'Teachers Leave School Districts, by Experience (linear',
                  'probability models; standard errors in parentheses)'),
  groups = list('Campus average student characteristics' = 3:6,
                'Interactions' = 7:10), 
  reorder.coef = c(1, 6, 2:5, 7:10),
  include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE))

idx = grep('years', tbl)
tbl = c(tbl[1L:(idx - 1L)],
        ' & \\multicolumn{4}{c}{Teacher Experience} \\\\ \\cline{2-5}',
        tbl[idx:length(tbl)])

idx = grep('^Num.*obs', tbl)
#print-formatting 1k+ numbers
tbl[idx] = gsub('(\\d{1,3})(?=\\d{3}+(?!\\d))', '\\1,', tbl[idx], perl = TRUE)
tbl[idx] = gsub('Num. obs.   ', 'Observations', tbl[idx], fixed = TRUE)

#exclude the extra blank rows introduced by texreg's group option
cat(tbl[grep('[^ &\\]', tbl)], sep = '\n')
```

```{r table_8, results = 'asis', cache = TRUE}
reg_l = 
  lapply(split(teachers, by = 'exp_split', sorted = TRUE),
         function(DT) DT[ , lm(move_district_next ~
                                 schedule_lbase_ba_salary*gender + 
                                 pct_prof_s + pct_frl_s + 
                                 ethnicity_main*pct_black_s + 
                                 ethnicity_main*pct_hisp_s + factor(year) + 
                                 factor(district_fill) + total_exp_floor + 
                                 I(total_exp_floor^2) +
                                 n_students_d + class_size_d)])

#some districts are dropped by lm
#  (insufficient variation given low frequency of moves & other covariates)
coefn = setNames(nm = Reduce(union, lapply(reg_l, function(x) names(coef(x)))))
coefn[seq_len(length(coefn))] = 'x'
idx = match(c('schedule_lbase_ba_salary', 'schedule_lbase_ba_salary:genderF',
              'pct_prof_s', 'pct_frl_s', 'pct_black_s', 'pct_hisp_s',
              paste0('ethnicity_main', 
                     c('Black', 'Black', 'Hispanic', 'Hispanic'), ':pct_',
                     c('black', 'hisp', 'black', 'hisp'), '_s')), names(coefn))
coefn[idx] = 
  c('First year base salary (log)', 'First year base salary (log) * female',
    'Percent proficient', 'Percent eligible for subsidized lunch',
    'Percent Black', 'Percent Hispanic', 'Black * percent Black',
    'Black * percent Hispanic', 'Hispanic * percent Black',
    'Hispanic * percent Hispanic')
reg_l = lapply(reg_l, function(x) {
  names(x$coefficients) = coefn[names(coef(x))]; x})
tbl = capture.output(texreg(
  reg_l, omit.coef = '^x', label = 'tbl:reg_lpm_fe', 
  caption = paste('Estimated Effects of Starting Teacher Salary and Student',
                  'Demographic Characteristics on the Probability that',
                  'Teachers Leave School Districts with District Fixed',
                  'Effects, by Experience (linear probability models;',
                  'standard errors in parentheses)'),
  groups = list('Campus average student characteristics' = 3:6,
                'Interactions' = 7:10), 
  reorder.coef = c(1, 6, 2:5, 7:10),
  include.rsquared = FALSE, include.adjrs = FALSE, include.rmse = FALSE))

idx = grep('years', tbl)
tbl = c(tbl[1L:(idx - 1L)],
        ' & \\multicolumn{4}{c}{Teacher Experience} \\\\ \\cline{2-5}',
        tbl[idx:length(tbl)])
idx = grep('^Num.*obs', tbl)
#print-formatting 1k+ numbers
tbl[idx] = gsub('(\\d{1,3})(?=\\d{3}+(?!\\d))', '\\1,', tbl[idx], perl = TRUE)
tbl[idx] = gsub('Num. obs.   ', 'Observations', tbl[idx], fixed = TRUE)
#exclude the extra blank rows introduced by texreg's group option
cat(tbl[grep('[^ &\\]', tbl)], sep = '\n')
```

```{r table_9, eval = FALSE}
library(mlogit)
teachersML = 
  melt(teachers, id.vars =
         c('teacher_id', 'year', 'schedule_lbase_ba_salary', 
           'gender', 'pct_prof_s', 'pct_frl_s', 'urbanicity_s',
           'ethnicity_main', 'pct_black_s', 'pct_hisp_s',
           'total_exp_floor', 'n_students_d', 'class_size_d','exp_split'), 
       measure.vars = c('stay_next', 'move_district_next', 'quit_next'),
       variable.name = 'alternative', value.name = 'chosen')
setorder(teachersML, teacher_id, year, alternative)

teachersML[ , ID := .GRP, by = .(teacher_id, year)]

mnl_l = 
  lapply(split(teachersML, by = 'exp_split', sorted = TRUE), function(DT) {
    print(head(DT))
    setattr(DT, 'class', c('mlogit.data', class(DT)))
    setattr(DT, 'index', with(DT, data.table(alt = alternative, chid = ID)))
    mlogit(chosen ~ 0 | 
             schedule_lbase_ba_salary*gender + pct_prof_s + pct_frl_s + 
             ethnicity_main*pct_black_s + ethnicity_main*pct_hisp_s + 
             #need to include dummy for year, but solution fails
             urbanicity_s + total_exp_floor + 
             I(total_exp_floor^2) + n_students_d + class_size_d, data = DT)
  })
texreg(mnl_l)
```

# Conclusion

# References
